from omuchat.const import IDENTIFIER

CHAT_PERMISSION = IDENTIFIER / "chat"
CHAT_READ_PERMISSION = CHAT_PERMISSION / "read"
CHAT_WRITE_PERMISSION = CHAT_PERMISSION / "write"
CHAT_SEND_PERMISSION = CHAT_PERMISSION / "send"
