name: PyPI

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.x"

      - name: Install rye
        uses: eifinger/setup-rye@v2.5.2
        with:
          enable-cache: true
          cache-prefix: "rye"

      - name: Install dependencies
        run: |
          rye sync

      - name: Build
        run: |
          rye build --all

      - name: Publish a Python distribution to PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine
          python -m twine upload --repository pypi --username __token__ --password ${{ secrets.PYPI_API_TOKEN }} dist/*
