name: PyPI

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install rye
        uses: eifinger/setup-rye@v2.2.0
        with:
          enable-cache: true
          cache-prefix: "rye"
      - name: Install dependencies
        run: |
          rye sync
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.lock') }}
      - name: Build
        run: |
          rye build --all
      - name: Publish a Python distribution to PyPI
        run: |
          rye publish --username __token__ --token ${{ secrets.PYPI_API_TOKEN }} -y
